export enum AccidentActionTypes {
  FETCH_ACCIDENT = "FETCH_ACCIDENT",
  FETCH_ACCIDENT_SUCCESS = "FETCH_ACCIDENT_SUCCESS",
  FETCH_ACCIDENT_ERROR = "FETCH_ACCIDENT_ERROR",
  FETCH_SINGLE_DATA = "FETCH_SINGLE_DATA",
}
